### ISSUE TITLE
"Issueベースの開発" レビュー依頼

### ISSUE THREAD

**Issue by sumisumi2000** [sumisumi2000/WishWay#146]
### 概要

MVP までの issue を作成しました。
すでに実装済みの機能はチェックマークをつけました。
レビューよろしくお願いいたします。

### 実装予定の機能
- [x] バケットリストの閲覧機能
- [x] ユーザー登録機能
- [x] ログイン機能
- バケットリスト
  - 作成機能
    - [x] ユーザー作成の際に自動的にリストも作成 
  -  編集機能
     - [x] リストのタイトル（一覧ページへの表示名）を編集
  - 削除機能
    - [x] リストを削除すると、ユーザーも自動的に削除
  - [x] 公開設定 一覧ページに公開するかどうかを設定
- 「やりたいこと」Wish の作成機能
  - [x] 編集機能
  - [x] 削除機能
  - [x] 作成日と達成日の表示
- [x] X（旧 Twitter）へのシェア機能
- [ ] パスワードリセット

### 必要なページ
- [x] トップページ
- [x] ログインページ
- [x] 新規登録ページ
- [x] リスト一覧ページ
- [x] リスト詳細ページ
- [x] マイリストページ
- [ ] パスワードリセットの申請ページ
- [ ] パスワードの再設定ページ

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。

> MVP までの issue を作成しました。
すでに実装済みの機能はチェックマークをつけました。
レビューよろしくお願いいたします。

上記、承知しました。
実装状況もGitHubProjectsからわかるようにしたいため、`Done`列にすでに実装してある機能のissueも作成していただいてよろしいでしょうか？
よろしくお願いします、

**Comment by sumisumi2000** [comment]
レビューありがとうございます。

Done 列にすでに実装してある機能の issue を作成いたしました。
また実装済みの機能の中で抜け漏れが見つかったため、Todo に issue を１つ追加しました。

レビューよろしくお願いいたします。

**Comment by tarakish** [comment]
確認できました。
「パスワードリセット機能」にストーリーポイント`5`がついていますが、ユーザーの新規登録機能やログイン機能が`2`とするとその2.5倍の見積もりになるということになりますが、その認識で合っているか一度ご確認をお願いします。
また、もしストーリーポイントの基準とされているIssueがあれば教えていただけると助かります！

**Comment by sumisumi2000** [comment]
レビューありがとうございます。

ストーリーポイントの基準にしたものは以下の通りです。

---
カリキュラムの Rails 基礎20 で開発環境でのパスワードリセットを実装したことがあり、その時は6時間ほどかかりました。
カリキュラムにかかった時間を基準にし、以下の項目を加味して `5` としておりました。
- 本番環境での開発は未経験
- 新規ページを２ページ作成するので、デザインを整えるのに時間がかかると考えた
  - アプリを開発してて気づいたのだが、自分の場合、機能の実装よりデザインに時間がかかっていることが多い
---

しかし、ご指摘の通りユーザーの新規登録機能やログイン機能に比べて 2.5 倍ではないなと感じたので、 `4` に変更いたしました。
レビューよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

**Comment by sumisumi2000** [comment]
ありがとうございます！
