### ISSUE TITLE
MVP リリース　レビュー依頼

### ISSUE THREAD

**Issue by sumisumi2000** [sumisumi2000/WishWay#171]
MVP リリース用の issue を作成いたしました。
レビューをよろしくお願いいたします。

---
## 各種情報
サービス名：WishWay
サービスURL：https://wishway.onrender.com
GitHub URL：https://github.com/sumisumi2000/WishWay

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] バケットリストの閲覧機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] バケットリスト
  - [ ] 作成機能
    - [ ] ユーザー作成の際に自動的にリストも作成
  - [ ] 編集機能
    - [ ] リストのタイトル（一覧ページへの表示名）を編集
- [ ] 削除機能
  - [ ] リストを削除すると、ユーザーも自動的に削除
- [ ] 公開設定 
  - [ ] 一覧ページに公開するかどうかを設定
- [ ] 「やりたいこと」Wish
  - [ ] 作成機能
  - [ ] 編集機能
  - [ ] 削除機能
  - [ ] 作成日と達成日の表示
- [ ] X（旧 Twitter）へのシェア機能
- [ ] パスワードリセット

### 必要なページ
- [ ] トップページ
- [ ] ログインページ
- [ ] 新規登録ページ
- [ ] リスト一覧ページ
- [ ] リスト詳細ページ
- [ ] マイリストページ
- [ ] パスワードリセットの申請ページ
- [ ] パスワードの再設定ページ

## サービスイメージがわかるようなスクリーンショット等

|                                   ログイン前トップページ                                   |                                   ログイン後トップページ                                    |
| :------------------------------------------------------------------------------: | :------------------------------------------------------------------------------: |
| ![](https://i.gyazo.com/7f3d3655c01879d17672746566af057b.png) | ![](https://i.gyazo.com/39c30289e77d42d40e47db1b50c052b4.png) |

|                                   新規登録ページ                                   |                                   ログインページ                                    |
| :------------------------------------------------------------------------------: | :------------------------------------------------------------------------------: |
| ![](https://i.gyazo.com/6f5374a056c7db646e5d379fbf01a218.png) | ![](https://i.gyazo.com/dbfe2423d0daf30ba4136c9f201835cc.png) |

|                                   パスワードリセット申請                                    |                                   パスワードリセット                                    |
| :------------------------------------------------------------------------------: | :------------------------------------------------------------------------------: |
| ![](https://i.gyazo.com/5730e77e43a5c1d7fe73fd4efb461f91.png) | ![](https://i.gyazo.com/658a48dd200a8a047e676e5c6f4a79f6.png) |

|                                    リスト一覧                                    |                                   タイトル検索                                   |
| :------------------------------------------------------------------------------: | :------------------------------------------------------------------------------: |
| ![](https://i.gyazo.com/98c2b4e0a3c6e66179030b2c41ab089d.gif) |  ![](https://i.gyazo.com/260461f5cb25675a185102e056a897b1.gif) |

|                                   リストの編集                                   |                                   リストの削除                                   |
| :------------------------------------------------------------------------------: | :------------------------------------------------------------------------------: |
| ![](https://i.gyazo.com/549c21275590bce75600a04c7d399c23.gif) | ![](https://i.gyazo.com/165ba62a4a0941888124964ba181698a.gif) |

|                                   Wish の作成                                    |                                   Wish の達成                                    |
| :------------------------------------------------------------------------------: | :------------------------------------------------------------------------------: |
| ![](https://i.gyazo.com/af8766730404479b82109c3c70b62725.gif) | ![](https://i.gyazo.com/357d7a0d8db41580f1340a5e95b2a274.gif) |

|                                   Wish の編集                                    |                                   Wish の削除                                    |
| :------------------------------------------------------------------------------: | :------------------------------------------------------------------------------: |
| ![](https://i.gyazo.com/d86859d8304d5d702098566361e29fff.gif) | ![](https://i.gyazo.com/53dcd627d49101c2e3d1f07ad1487669.gif) |

**Comment by kenchasonakai** [comment]
LGTMです！

**Comment by sumisumi2000** [comment]
ありがとうございます！
